//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSOM_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class acces
    {
        public string CODE { get; set; }
        public Nullable<System.DateTime> EXPIRED { get; set; }
        public Nullable<int> ID_COMPTE { get; set; }
        public Nullable<System.DateTime> REC_TIME { get; set; }
        public Nullable<int> USED { get; set; }
        public int ID { get; set; }
    }
}
