//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSOM_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICLE
    {
        public ARTICLE()
        {
            this.LIGNE_PRIX = new HashSet<LIGNE_PRIX>();
        }
    
        public short CodeArticle { get; set; }
        public string LibArticle { get; set; }
        public string CCArticle { get; set; }
        public string CCArticleEx { get; set; }
        public Nullable<short> CodeFamArt { get; set; }
        public string CodeTVA { get; set; }
        public string CCarticle1 { get; set; }
        public string CCarticleEX1 { get; set; }
        public string Statut { get; set; }
    
        public virtual ICollection<LIGNE_PRIX> LIGNE_PRIX { get; set; }
    }
}
