//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSOM_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCALE
    {
        public int IdEsc { get; set; }
        public Nullable<int> NumEsc { get; set; }
        public string NumVoySCR { get; set; }
        public string NumVoyDIT { get; set; }
        public string NomCpt { get; set; }
        public Nullable<System.DateTime> DCEsc { get; set; }
        public Nullable<System.DateTime> DDEsc { get; set; }
        public Nullable<System.DateTime> DPAEsc { get; set; }
        public Nullable<System.DateTime> DRAEsc { get; set; }
        public Nullable<System.DateTime> DDechEsc { get; set; }
        public Nullable<short> NbrePManEsc { get; set; }
        public string RGPEsc { get; set; }
        public string RREsc { get; set; }
        public string RAEsc { get; set; }
        public string RCEsc { get; set; }
        public string AIEsc { get; set; }
        public string SOP { get; set; }
        public Nullable<int> IdNav { get; set; }
        public Nullable<int> IdArm { get; set; }
        public Nullable<int> IdAcc { get; set; }
        public Nullable<int> IdFArm { get; set; }
        public Nullable<System.DateTime> DateFArm { get; set; }
        public string StatEsc { get; set; }
        public Nullable<System.DateTime> SailingDate { get; set; }
        public string NumManifestSydonia { get; set; }
        public Nullable<int> IdUserFIntern { get; set; }
        public string FIntern { get; set; }
    }
}
