//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSOM_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURE
    {
        public FACTURE()
        {
            this.PAYEMENTs = new HashSet<PAYEMENT>();
        }
    
        public int IdFD { get; set; }
        public string RefAS400 { get; set; }
        public Nullable<System.DateTime> DCFD { get; set; }
        public Nullable<System.DateTime> DEFD { get; set; }
        public string StatutFD { get; set; }
        public Nullable<int> MHT { get; set; }
        public Nullable<int> MTVA { get; set; }
        public Nullable<int> MTTC { get; set; }
        public Nullable<int> IdFP { get; set; }
        public Nullable<int> IdU { get; set; }
        public Nullable<int> IdClient { get; set; }
        public string AIFD { get; set; }
        public Nullable<int> IdPay { get; set; }
        public Nullable<System.DateTime> DateComptable { get; set; }
        public Nullable<int> IdDocSAP { get; set; }
    
        public virtual PROFORMA PROFORMA { get; set; }
        public virtual ICollection<PAYEMENT> PAYEMENTs { get; set; }
    }
}
