//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSOM_API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class INHOUSEAPPEntities1 : DbContext
    {
        public INHOUSEAPPEntities1()
            : base("name=INHOUSEAPPEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<POINTAGES> POINTAGES { get; set; }
        public DbSet<PRM_CALENDRE> PRM_CALENDRE { get; set; }
        public DbSet<PRM_EMPL> PRM_EMPL { get; set; }
        public DbSet<PRM_GROUPE> PRM_GROUPE { get; set; }
        public DbSet<PRM_PERIODE> PRM_PERIODE { get; set; }
        public DbSet<PRM_PROGRAM> PRM_PROGRAM { get; set; }
        public DbSet<PRM_SVC> PRM_SVC { get; set; }
        public DbSet<PRM_SVC_HOUR> PRM_SVC_HOUR { get; set; }
    
        public virtual ObjectResult<EmplWeekStat_Result> EmplWeekStat(Nullable<int> idempl, Nullable<int> idweek)
        {
            var idemplParameter = idempl.HasValue ?
                new ObjectParameter("idempl", idempl) :
                new ObjectParameter("idempl", typeof(int));
    
            var idweekParameter = idweek.HasValue ?
                new ObjectParameter("idweek", idweek) :
                new ObjectParameter("idweek", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmplWeekStat_Result>("EmplWeekStat", idemplParameter, idweekParameter);
        }
    }
}
