//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSOM_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIGNE_PRIX
    {
        public LIGNE_PRIX()
        {
            this.ELEMENT_FACTURATION = new HashSet<ELEMENT_FACTURATION>();
        }
    
        public int IdLP { get; set; }
        public string CodeLP { get; set; }
        public Nullable<short> CodeArticle { get; set; }
        public string DescLP { get; set; }
        public Nullable<int> PU1LP { get; set; }
        public Nullable<int> PU2LP { get; set; }
        public Nullable<int> PU3LP { get; set; }
        public Nullable<int> PU4LP { get; set; }
        public Nullable<int> PU5LP { get; set; }
        public Nullable<System.DateTime> DDLP { get; set; }
        public Nullable<System.DateTime> DFLP { get; set; }
        public string UniteLP { get; set; }
        public string LP { get; set; }
        public string LP2 { get; set; }
        public string Regle { get; set; }
    
        public virtual ARTICLE ARTICLE { get; set; }
        public virtual ICollection<ELEMENT_FACTURATION> ELEMENT_FACTURATION { get; set; }
    }
}
