//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSOM_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int ID { get; set; }
        public string CLIENT { get; set; }
        public string COMPTES { get; set; }
        public Nullable<System.DateTime> REC { get; set; }
        public string TYP { get; set; }
        public string DESCRIPTION { get; set; }
        public string SOURCE { get; set; }
    }
}
