//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSOM_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class POINTAGES
    {
        public int IDAUTO { get; set; }
        public int ID_EMPL { get; set; }
        public int ID_PERIODE { get; set; }
        public System.DateTime JOUR { get; set; }
        public System.TimeSpan MHE { get; set; }
        public System.TimeSpan MHS { get; set; }
        public int OP { get; set; }
        public System.DateTime DATE_ENREG { get; set; }
        public int VALID { get; set; }
        public int VISA { get; set; }
        public System.TimeSpan SHE { get; set; }
        public System.TimeSpan SHS { get; set; }
        public int DIFF { get; set; }
        public int HN { get; set; }
        public int T120 { get; set; }
        public int T140 { get; set; }
        public int T150 { get; set; }
        public int T200 { get; set; }
        public int HM { get; set; }
        public int IDCAL { get; set; }
        public int T130 { get; set; }
        public Nullable<System.TimeSpan> HNE { get; set; }
        public Nullable<int> SHIFT { get; set; }
    
        public virtual PRM_EMPL PRM_EMPL { get; set; }
        public virtual PRM_PERIODE PRM_PERIODE { get; set; }
    }
}
