//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSOM_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_PERIODE
    {
        public PRM_PERIODE()
        {
            this.POINTAGES = new HashSet<POINTAGES>();
            this.PRM_PROGRAM = new HashSet<PRM_PROGRAM>();
        }
    
        public int IDAUTO { get; set; }
        public System.DateTime DEBUT { get; set; }
        public System.DateTime FIN { get; set; }
        public int ANNEE { get; set; }
        public int STATUT { get; set; }
    
        public virtual ICollection<POINTAGES> POINTAGES { get; set; }
        public virtual ICollection<PRM_PROGRAM> PRM_PROGRAM { get; set; }
    }
}
