//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSOM_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_SVC_HOUR
    {
        public int IDSERVICE { get; set; }
        public int OP { get; set; }
        public System.TimeSpan ME { get; set; }
        public System.TimeSpan MS { get; set; }
        public Nullable<System.TimeSpan> SE { get; set; }
        public Nullable<System.TimeSpan> SS { get; set; }
    }
}
