//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSOM_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_PROGRAM
    {
        public int IDAUTO { get; set; }
        public int IDPERIODE { get; set; }
        public System.DateTime JOUR { get; set; }
        public int FERIE { get; set; }
        public int OP { get; set; }
        public System.DateTime DATE_ENREG { get; set; }
        public string LIBELLE { get; set; }
    
        public virtual PRM_PERIODE PRM_PERIODE { get; set; }
    }
}
