//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSOM_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_EMPL
    {
        public PRM_EMPL()
        {
            this.POINTAGES = new HashSet<POINTAGES>();
        }
    
        public int IDAUTO { get; set; }
        public string NOM { get; set; }
        public string PRENOMS { get; set; }
        public int MLE { get; set; }
        public Nullable<System.DateTime> DATE_ENREG { get; set; }
        public string STATUS { get; set; }
        public int IDSERVICE { get; set; }
    
        public virtual ICollection<POINTAGES> POINTAGES { get; set; }
    }
}
