//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSOM_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRM_CALENDRE
    {
        public int IDAUTO { get; set; }
        public System.DateTime DEBUT { get; set; }
        public System.DateTime FIN { get; set; }
        public System.DateTime DATE_ENREG { get; set; }
        public int IDPRD { get; set; }
    }
}
