//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSOM_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class quotation
    {
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string LEVEL { get; set; }
        public string BL { get; set; }
        public string CHASSIS { get; set; }
        public Nullable<System.DateTime> REC_DATE { get; set; }
        public string STATUT { get; set; }
        public int COMPTES_ID { get; set; }
        public Nullable<int> HT { get; set; }
        public Nullable<int> TVA { get; set; }
        public Nullable<int> TTC { get; set; }
        public int ID { get; set; }
    }
}
