//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSOM_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULE
    {
        public int IdVeh { get; set; }
        public string NumChassis { get; set; }
        public string NumChassisSGS { get; set; }
        public string BarCode { get; set; }
        public Nullable<System.DateTime> DCVeh { get; set; }
        public string DescVeh { get; set; }
        public string CouleurVeh { get; set; }
        public string TypeMVeh { get; set; }
        public string StatutVeh { get; set; }
        public Nullable<int> PoidsMVeh { get; set; }
        public Nullable<double> VolMVeh { get; set; }
        public Nullable<float> LongMVeh { get; set; }
        public Nullable<float> LargMVeh { get; set; }
        public Nullable<float> HautMVeh { get; set; }
        public Nullable<short> NumItem { get; set; }
        public string InfoMan { get; set; }
        public string TypeCVeh { get; set; }
        public Nullable<int> PoidsCVeh { get; set; }
        public Nullable<double> VolCVeh { get; set; }
        public Nullable<float> LongCVeh { get; set; }
        public Nullable<float> LargCVeh { get; set; }
        public Nullable<float> HautCVeh { get; set; }
        public string StatutCVeh { get; set; }
        public string VehPorte { get; set; }
        public string VehAttelle { get; set; }
        public string VehCle { get; set; }
        public string VehStart { get; set; }
        public string VehChargé { get; set; }
        public Nullable<int> IdVehAP { get; set; }
        public string StatVeh { get; set; }
        public Nullable<System.DateTime> FFVeh { get; set; }
        public Nullable<System.DateTime> FSVeh { get; set; }
        public Nullable<System.DateTime> DSPVeh { get; set; }
        public Nullable<System.DateTime> DSRVeh { get; set; }
        public Nullable<System.DateTime> DateVAE { get; set; }
        public Nullable<int> IdBL { get; set; }
        public Nullable<int> IdMan { get; set; }
        public Nullable<int> IdEsc { get; set; }
        public Nullable<int> IdAcc { get; set; }
        public Nullable<int> IdBAE { get; set; }
        public Nullable<int> IdDBL { get; set; }
        public Nullable<int> IdBS { get; set; }
        public string NomEnVeh { get; set; }
        public string CNIEnVeh { get; set; }
        public string TelenVeh { get; set; }
        public string NumADDVeh { get; set; }
        public string NumCIVIOveh { get; set; }
        public string NumDDVeh { get; set; }
        public string NumQDVeh { get; set; }
        public string NumFPADVeh { get; set; }
        public string NumQPADVeh { get; set; }
        public string NumAEPADVeh { get; set; }
        public string NumBESCVeh { get; set; }
        public string NumSydoniaVeh { get; set; }
        public string SensVeh { get; set; }
        public string AIVeh { get; set; }
    
        public virtual CONNAISSEMENT CONNAISSEMENT { get; set; }
    }
}
