//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.6407
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Awmds {
    
    private AwmdsGeneral_segment general_segmentField;
    
    private AwmdsBol_segment[] bol_segmentField;
    
    /// <remarks/>
    public AwmdsGeneral_segment General_segment {
        get {
            return this.general_segmentField;
        }
        set {
            this.general_segmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Bol_segment")]
    public AwmdsBol_segment[] Bol_segment {
        get {
            return this.bol_segmentField;
        }
        set {
            this.bol_segmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsGeneral_segment {
    
    private AwmdsGeneral_segmentGeneral_segment_id general_segment_idField;
    
    private AwmdsGeneral_segmentTotals_segment totals_segmentField;
    
    private AwmdsGeneral_segmentTransport_information transport_informationField;
    
    private AwmdsGeneral_segmentLoad_unload_place load_unload_placeField;
    
    private AwmdsGeneral_segmentTonnage tonnageField;
    
    /// <remarks/>
    public AwmdsGeneral_segmentGeneral_segment_id General_segment_id {
        get {
            return this.general_segment_idField;
        }
        set {
            this.general_segment_idField = value;
        }
    }
    
    /// <remarks/>
    public AwmdsGeneral_segmentTotals_segment Totals_segment {
        get {
            return this.totals_segmentField;
        }
        set {
            this.totals_segmentField = value;
        }
    }
    
    /// <remarks/>
    public AwmdsGeneral_segmentTransport_information Transport_information {
        get {
            return this.transport_informationField;
        }
        set {
            this.transport_informationField = value;
        }
    }
    
    /// <remarks/>
    public AwmdsGeneral_segmentLoad_unload_place Load_unload_place {
        get {
            return this.load_unload_placeField;
        }
        set {
            this.load_unload_placeField = value;
        }
    }
    
    /// <remarks/>
    public AwmdsGeneral_segmentTonnage Tonnage {
        get {
            return this.tonnageField;
        }
        set {
            this.tonnageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsGeneral_segmentGeneral_segment_id {
    
    private string customs_office_codeField;
    
    private string voyage_numberField;
    
    private string date_of_departureField;
    
    private string date_of_arrivalField;
    
    private string time_of_arrivalField;
    
    /// <remarks/>
    public string Customs_office_code {
        get {
            return this.customs_office_codeField;
        }
        set {
            this.customs_office_codeField = value;
        }
    }
    
    /// <remarks/>
    public string Voyage_number {
        get {
            return this.voyage_numberField;
        }
        set {
            this.voyage_numberField = value;
        }
    }
    
    /// <remarks/>
    public string Date_of_departure {
        get {
            return this.date_of_departureField;
        }
        set {
            this.date_of_departureField = value;
        }
    }
    
    /// <remarks/>
    public string Date_of_arrival {
        get {
            return this.date_of_arrivalField;
        }
        set {
            this.date_of_arrivalField = value;
        }
    }
    
    /// <remarks/>
    public string Time_of_arrival {
        get {
            return this.time_of_arrivalField;
        }
        set {
            this.time_of_arrivalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsGeneral_segmentTotals_segment {
    
    private int total_number_of_bolsField;
    
    private int total_number_of_packagesField;
    
    private int total_number_of_containersField;
    
    private double total_gross_massField;
    
    /// <remarks/>
    public int Total_number_of_bols {
        get {
            return this.total_number_of_bolsField;
        }
        set {
            this.total_number_of_bolsField = value;
        }
    }
    
    /// <remarks/>
    public int Total_number_of_packages {
        get {
            return this.total_number_of_packagesField;
        }
        set {
            this.total_number_of_packagesField = value;
        }
    }
    
    /// <remarks/>
    public int Total_number_of_containers {
        get {
            return this.total_number_of_containersField;
        }
        set {
            this.total_number_of_containersField = value;
        }
    }
    
    /// <remarks/>
    public double Total_gross_mass {
        get {
            return this.total_gross_massField;
        }
        set {
            this.total_gross_massField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsGeneral_segmentTransport_information {
    
    private AwmdsGeneral_segmentTransport_informationCarrier carrierField;
    
    private string mode_of_transport_codeField;
    
    private string identity_of_transporterField;
    
    private string nationality_of_transporter_codeField;
    
    private string place_of_transporterField;
    
    private string registration_number_of_transport_codeField;
    
    private object date_of_registrationField;
    
    private string master_informationField;
    
    /// <remarks/>
    public AwmdsGeneral_segmentTransport_informationCarrier Carrier {
        get {
            return this.carrierField;
        }
        set {
            this.carrierField = value;
        }
    }
    
    /// <remarks/>
    public string Mode_of_transport_code {
        get {
            return this.mode_of_transport_codeField;
        }
        set {
            this.mode_of_transport_codeField = value;
        }
    }
    
    /// <remarks/>
    public string Identity_of_transporter {
        get {
            return this.identity_of_transporterField;
        }
        set {
            this.identity_of_transporterField = value;
        }
    }
    
    /// <remarks/>
    public string Nationality_of_transporter_code {
        get {
            return this.nationality_of_transporter_codeField;
        }
        set {
            this.nationality_of_transporter_codeField = value;
        }
    }
    
    /// <remarks/>
    public string Place_of_transporter {
        get {
            return this.place_of_transporterField;
        }
        set {
            this.place_of_transporterField = value;
        }
    }
    
    /// <remarks/>
    public string Registration_number_of_transport_code {
        get {
            return this.registration_number_of_transport_codeField;
        }
        set {
            this.registration_number_of_transport_codeField = value;
        }
    }
    
    /// <remarks/>
    public object Date_of_registration {
        get {
            return this.date_of_registrationField;
        }
        set {
            this.date_of_registrationField = value;
        }
    }
    
    /// <remarks/>
    public string Master_information {
        get {
            return this.master_informationField;
        }
        set {
            this.master_informationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsGeneral_segmentTransport_informationCarrier {
    
    private string carrier_codeField;
    
    private string carrier_nameField;
    
    private string carrier_address1Field;
    
    /// <remarks/>
    public string Carrier_code {
        get {
            return this.carrier_codeField;
        }
        set {
            this.carrier_codeField = value;
        }
    }
    
    /// <remarks/>
    public string Carrier_name {
        get {
            return this.carrier_nameField;
        }
        set {
            this.carrier_nameField = value;
        }
    }
    
    /// <remarks/>
    public string Carrier_address1 {
        get {
            return this.carrier_address1Field;
        }
        set {
            this.carrier_address1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsGeneral_segmentLoad_unload_place {
    
    private string place_of_departure_codeField;
    
    private string place_of_destination_codeField;
    
    /// <remarks/>
    public string Place_of_departure_code {
        get {
            return this.place_of_departure_codeField;
        }
        set {
            this.place_of_departure_codeField = value;
        }
    }
    
    /// <remarks/>
    public string Place_of_destination_code {
        get {
            return this.place_of_destination_codeField;
        }
        set {
            this.place_of_destination_codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsGeneral_segmentTonnage {
    
    private double tonnage_net_weightField;
    
    private double tonnage_gross_weightField;
    
    /// <remarks/>
    public double Tonnage_net_weight {
        get {
            return this.tonnage_net_weightField;
        }
        set {
            this.tonnage_net_weightField = value;
        }
    }
    
    /// <remarks/>
    public double Tonnage_gross_weight {
        get {
            return this.tonnage_gross_weightField;
        }
        set {
            this.tonnage_gross_weightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segment {
    
    private AwmdsBol_segmentBol_id bol_idField;
    
    private AwmdsBol_segmentLoad_unload_place load_unload_placeField;
    
    private AwmdsBol_segmentTraders_segment traders_segmentField;
    
    private AwmdsBol_segmentCtn_segment[] ctn_segmentField;
    
    private AwmdsBol_segmentGoods_segment goods_segmentField;
    
    private AwmdsBol_segmentValue_segment value_segmentField;
    
    private AwmdsBol_segmentLocation locationField;
    
    /// <remarks/>
    public AwmdsBol_segmentBol_id Bol_id {
        get {
            return this.bol_idField;
        }
        set {
            this.bol_idField = value;
        }
    }
    
    /// <remarks/>
    public AwmdsBol_segmentLoad_unload_place Load_unload_place {
        get {
            return this.load_unload_placeField;
        }
        set {
            this.load_unload_placeField = value;
        }
    }
    
    /// <remarks/>
    public AwmdsBol_segmentTraders_segment Traders_segment {
        get {
            return this.traders_segmentField;
        }
        set {
            this.traders_segmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ctn_segment")]
    public AwmdsBol_segmentCtn_segment[] ctn_segment {
        get {
            return this.ctn_segmentField;
        }
        set {
            this.ctn_segmentField = value;
        }
    }
    
    /// <remarks/>
    public AwmdsBol_segmentGoods_segment Goods_segment {
        get {
            return this.goods_segmentField;
        }
        set {
            this.goods_segmentField = value;
        }
    }
    
    /// <remarks/>
    public AwmdsBol_segmentValue_segment Value_segment {
        get {
            return this.value_segmentField;
        }
        set {
            this.value_segmentField = value;
        }
    }
    
    /// <remarks/>
    public AwmdsBol_segmentLocation Location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segmentBol_id {
    
    private string bol_referenceField;
    
    private AwmdsBol_segmentBol_idBol_nature bol_natureField;
    
    private string bol_type_codeField;
    
    /// <remarks/>
    public string Bol_reference {
        get {
            return this.bol_referenceField;
        }
        set {
            this.bol_referenceField = value;
        }
    }
    
    /// <remarks/>
    public AwmdsBol_segmentBol_idBol_nature Bol_nature {
        get {
            return this.bol_natureField;
        }
        set {
            this.bol_natureField = value;
        }
    }
    
    /// <remarks/>
    public string Bol_type_code {
        get {
            return this.bol_type_codeField;
        }
        set {
            this.bol_type_codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum AwmdsBol_segmentBol_idBol_nature {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("22")]
    Item22,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("23")]
    Item23,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("24")]
    Item24,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("28")]
    Item28,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segmentLoad_unload_place {
    
    private string place_of_loading_codeField;
    
    private string place_of_unloading_codeField;
    
    /// <remarks/>
    public string Place_of_loading_code {
        get {
            return this.place_of_loading_codeField;
        }
        set {
            this.place_of_loading_codeField = value;
        }
    }
    
    /// <remarks/>
    public string Place_of_unloading_code {
        get {
            return this.place_of_unloading_codeField;
        }
        set {
            this.place_of_unloading_codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segmentTraders_segment {
    
    private AwmdsBol_segmentTraders_segmentExporter exporterField;
    
    private AwmdsBol_segmentTraders_segmentNotify notifyField;
    
    private AwmdsBol_segmentTraders_segmentConsignee consigneeField;
    
    /// <remarks/>
    public AwmdsBol_segmentTraders_segmentExporter Exporter {
        get {
            return this.exporterField;
        }
        set {
            this.exporterField = value;
        }
    }
    
    /// <remarks/>
    public AwmdsBol_segmentTraders_segmentNotify Notify {
        get {
            return this.notifyField;
        }
        set {
            this.notifyField = value;
        }
    }
    
    /// <remarks/>
    public AwmdsBol_segmentTraders_segmentConsignee Consignee {
        get {
            return this.consigneeField;
        }
        set {
            this.consigneeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segmentTraders_segmentExporter {
    
    private string exporter_nameField;
    
    private string exporter_address1Field;
    
    /// <remarks/>
    public string Exporter_name {
        get {
            return this.exporter_nameField;
        }
        set {
            this.exporter_nameField = value;
        }
    }
    
    /// <remarks/>
    public string Exporter_address1 {
        get {
            return this.exporter_address1Field;
        }
        set {
            this.exporter_address1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segmentTraders_segmentNotify {
    
    private string notify_codeField;
    
    private string notify_nameField;
    
    private string notify_address1Field;
    
    private string notify_address2Field;
    
    private string notify_address3Field;
    
    private string notify_address4Field;
    
    /// <remarks/>
    public string Notify_code {
        get {
            return this.notify_codeField;
        }
        set {
            this.notify_codeField = value;
        }
    }
    
    /// <remarks/>
    public string Notify_name {
        get {
            return this.notify_nameField;
        }
        set {
            this.notify_nameField = value;
        }
    }
    
    /// <remarks/>
    public string Notify_address1 {
        get {
            return this.notify_address1Field;
        }
        set {
            this.notify_address1Field = value;
        }
    }
    
    /// <remarks/>
    public string Notify_address2 {
        get {
            return this.notify_address2Field;
        }
        set {
            this.notify_address2Field = value;
        }
    }
    
    /// <remarks/>
    public string Notify_address3 {
        get {
            return this.notify_address3Field;
        }
        set {
            this.notify_address3Field = value;
        }
    }
    
    /// <remarks/>
    public string Notify_address4 {
        get {
            return this.notify_address4Field;
        }
        set {
            this.notify_address4Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segmentTraders_segmentConsignee {
    
    private string consignee_codeField;
    
    private string consignee_nameField;
    
    private string consignee_address1Field;
    
    /// <remarks/>
    public string Consignee_code {
        get {
            return this.consignee_codeField;
        }
        set {
            this.consignee_codeField = value;
        }
    }
    
    /// <remarks/>
    public string Consignee_name {
        get {
            return this.consignee_nameField;
        }
        set {
            this.consignee_nameField = value;
        }
    }
    
    /// <remarks/>
    public string Consignee_address1 {
        get {
            return this.consignee_address1Field;
        }
        set {
            this.consignee_address1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segmentCtn_segment {
    
    private string ctn_referenceField;
    
    private int number_of_packagesField;
    
    private string type_of_containerField;
    
    private string empty_FullField;
    
    private string marks1Field;
    
    private string marks2Field;
    
    private string marks3Field;
    
    private string sealing_PartyField;
    
    /// <remarks/>
    public string Ctn_reference {
        get {
            return this.ctn_referenceField;
        }
        set {
            this.ctn_referenceField = value;
        }
    }
    
    /// <remarks/>
    public int Number_of_packages {
        get {
            return this.number_of_packagesField;
        }
        set {
            this.number_of_packagesField = value;
        }
    }
    
    /// <remarks/>
    public string Type_of_container {
        get {
            return this.type_of_containerField;
        }
        set {
            this.type_of_containerField = value;
        }
    }
    
    /// <remarks/>
    public string Empty_Full {
        get {
            return this.empty_FullField;
        }
        set {
            this.empty_FullField = value;
        }
    }
    
    /// <remarks/>
    public string Marks1 {
        get {
            return this.marks1Field;
        }
        set {
            this.marks1Field = value;
        }
    }
    
    /// <remarks/>
    public string Marks2 {
        get {
            return this.marks2Field;
        }
        set {
            this.marks2Field = value;
        }
    }
    
    /// <remarks/>
    public string Marks3 {
        get {
            return this.marks3Field;
        }
        set {
            this.marks3Field = value;
        }
    }
    
    /// <remarks/>
    public string Sealing_Party {
        get {
            return this.sealing_PartyField;
        }
        set {
            this.sealing_PartyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segmentGoods_segment {
    
    private int number_of_packagesField;
    
    private string package_type_codeField;
    
    private double gross_massField;
    
    private string shipping_marksField;
    
    private double volume_in_cubic_metersField;
    
    private bool volume_in_cubic_metersFieldSpecified;
    
    private int num_of_ctn_for_this_bolField;
    
    private string informationField;
    
    private AwmdsBol_segmentGoods_segmentGoods_detail_segment[] goods_detail_segmentField;
    
    /// <remarks/>
    public int Number_of_packages {
        get {
            return this.number_of_packagesField;
        }
        set {
            this.number_of_packagesField = value;
        }
    }
    
    /// <remarks/>
    public string Package_type_code {
        get {
            return this.package_type_codeField;
        }
        set {
            this.package_type_codeField = value;
        }
    }
    
    /// <remarks/>
    public double Gross_mass {
        get {
            return this.gross_massField;
        }
        set {
            this.gross_massField = value;
        }
    }
    
    /// <remarks/>
    public string Shipping_marks {
        get {
            return this.shipping_marksField;
        }
        set {
            this.shipping_marksField = value;
        }
    }
    
    /// <remarks/>
    public double Volume_in_cubic_meters {
        get {
            return this.volume_in_cubic_metersField;
        }
        set {
            this.volume_in_cubic_metersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Volume_in_cubic_metersSpecified {
        get {
            return this.volume_in_cubic_metersFieldSpecified;
        }
        set {
            this.volume_in_cubic_metersFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int Num_of_ctn_for_this_bol {
        get {
            return this.num_of_ctn_for_this_bolField;
        }
        set {
            this.num_of_ctn_for_this_bolField = value;
        }
    }
    
    /// <remarks/>
    public string Information {
        get {
            return this.informationField;
        }
        set {
            this.informationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Goods_detail_segment")]
    public AwmdsBol_segmentGoods_segmentGoods_detail_segment[] Goods_detail_segment {
        get {
            return this.goods_detail_segmentField;
        }
        set {
            this.goods_detail_segmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segmentGoods_segmentGoods_detail_segment {
    
    private string package_type_codeField;
    
    private string goods_descriptionField;
    
    private string shipping_marksField;
    
    private double gross_massField;
    
    private int number_of_packagesField;
    
    private double volume_in_cubic_metersField;
    
    private AwmdsBol_segmentGoods_segmentGoods_detail_segmentSeals_segment seals_segmentField;
    
    /// <remarks/>
    public string Package_type_code {
        get {
            return this.package_type_codeField;
        }
        set {
            this.package_type_codeField = value;
        }
    }
    
    /// <remarks/>
    public string Goods_description {
        get {
            return this.goods_descriptionField;
        }
        set {
            this.goods_descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Shipping_marks {
        get {
            return this.shipping_marksField;
        }
        set {
            this.shipping_marksField = value;
        }
    }
    
    /// <remarks/>
    public double Gross_mass {
        get {
            return this.gross_massField;
        }
        set {
            this.gross_massField = value;
        }
    }
    
    /// <remarks/>
    public int Number_of_packages {
        get {
            return this.number_of_packagesField;
        }
        set {
            this.number_of_packagesField = value;
        }
    }
    
    /// <remarks/>
    public double Volume_in_cubic_meters {
        get {
            return this.volume_in_cubic_metersField;
        }
        set {
            this.volume_in_cubic_metersField = value;
        }
    }
    
    /// <remarks/>
    public AwmdsBol_segmentGoods_segmentGoods_detail_segmentSeals_segment Seals_segment {
        get {
            return this.seals_segmentField;
        }
        set {
            this.seals_segmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segmentGoods_segmentGoods_detail_segmentSeals_segment {
    
    private string marks_of_sealsField;
    
    /// <remarks/>
    public string Marks_of_seals {
        get {
            return this.marks_of_sealsField;
        }
        set {
            this.marks_of_sealsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segmentValue_segment {
    
    private AwmdsBol_segmentValue_segmentFreight_segment freight_segmentField;
    
    private AwmdsBol_segmentValue_segmentCustoms_segment customs_segmentField;
    
    private AwmdsBol_segmentValue_segmentInsurance_segment insurance_segmentField;
    
    private AwmdsBol_segmentValue_segmentTransport_segment transport_segmentField;
    
    /// <remarks/>
    public AwmdsBol_segmentValue_segmentFreight_segment Freight_segment {
        get {
            return this.freight_segmentField;
        }
        set {
            this.freight_segmentField = value;
        }
    }
    
    /// <remarks/>
    public AwmdsBol_segmentValue_segmentCustoms_segment Customs_segment {
        get {
            return this.customs_segmentField;
        }
        set {
            this.customs_segmentField = value;
        }
    }
    
    /// <remarks/>
    public AwmdsBol_segmentValue_segmentInsurance_segment Insurance_segment {
        get {
            return this.insurance_segmentField;
        }
        set {
            this.insurance_segmentField = value;
        }
    }
    
    /// <remarks/>
    public AwmdsBol_segmentValue_segmentTransport_segment Transport_segment {
        get {
            return this.transport_segmentField;
        }
        set {
            this.transport_segmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segmentValue_segmentFreight_segment {
    
    private string pC_indicatorField;
    
    private double freight_valueField;
    
    private string freight_currencyField;
    
    /// <remarks/>
    public string PC_indicator {
        get {
            return this.pC_indicatorField;
        }
        set {
            this.pC_indicatorField = value;
        }
    }
    
    /// <remarks/>
    public double Freight_value {
        get {
            return this.freight_valueField;
        }
        set {
            this.freight_valueField = value;
        }
    }
    
    /// <remarks/>
    public string Freight_currency {
        get {
            return this.freight_currencyField;
        }
        set {
            this.freight_currencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segmentValue_segmentCustoms_segment {
    
    private double customs_valueField;
    
    private bool customs_valueFieldSpecified;
    
    private string customs_currencyField;
    
    /// <remarks/>
    public double Customs_value {
        get {
            return this.customs_valueField;
        }
        set {
            this.customs_valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Customs_valueSpecified {
        get {
            return this.customs_valueFieldSpecified;
        }
        set {
            this.customs_valueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Customs_currency {
        get {
            return this.customs_currencyField;
        }
        set {
            this.customs_currencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segmentValue_segmentInsurance_segment {
    
    private double insurance_valueField;
    
    private bool insurance_valueFieldSpecified;
    
    private string insurance_currencyField;
    
    /// <remarks/>
    public double Insurance_value {
        get {
            return this.insurance_valueField;
        }
        set {
            this.insurance_valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Insurance_valueSpecified {
        get {
            return this.insurance_valueFieldSpecified;
        }
        set {
            this.insurance_valueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Insurance_currency {
        get {
            return this.insurance_currencyField;
        }
        set {
            this.insurance_currencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segmentValue_segmentTransport_segment {
    
    private double transport_valueField;
    
    private bool transport_valueFieldSpecified;
    
    private string transport_currencyField;
    
    /// <remarks/>
    public double Transport_value {
        get {
            return this.transport_valueField;
        }
        set {
            this.transport_valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Transport_valueSpecified {
        get {
            return this.transport_valueFieldSpecified;
        }
        set {
            this.transport_valueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Transport_currency {
        get {
            return this.transport_currencyField;
        }
        set {
            this.transport_currencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AwmdsBol_segmentLocation {
    
    private string location_codeField;
    
    private string location_infoField;
    
    /// <remarks/>
    public string Location_code {
        get {
            return this.location_codeField;
        }
        set {
            this.location_codeField = value;
        }
    }
    
    /// <remarks/>
    public string Location_info {
        get {
            return this.location_infoField;
        }
        set {
            this.location_infoField = value;
        }
    }
}
