//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverData
{
    using System;
    using System.Collections.Generic;
    
    public partial class compte_rule
    {
        public Nullable<System.DateTime> REC { get; set; }
        public int COMPTES_ID { get; set; }
        public int RULES_ID { get; set; }
    }
}
