//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverData
{
    using System;
    using System.Collections.Generic;
    
    public partial class requetes
    {
        public string LIBELLE { get; set; }
        public Nullable<System.DateTime> REC_TIME { get; set; }
        public Nullable<int> IDCOMPTES { get; set; }
        public string ETAT { get; set; }
        public int ID_QUOTATION { get; set; }
        public int ID { get; set; }
        public Nullable<int> IDFACTURE { get; set; }
    
        public virtual quotation quotation { get; set; }
    }
}
