<?xml version="1.0" encoding="utf-8"?><Database Name="SOCOMAR_PRODUCTION" Class="SAPDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=SOCOMAR_PRODUCTION;User ID=sa" SettingsObjectName="VesselStopOverData.Properties.Settings" SettingsPropertyName="SOCOMAR_PRODUCTIONConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.OINV" Member="OINV">
    <Type Name="OINV">
      <Column Name="DocEntry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DocNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DocType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CANCELED" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Handwrtten" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Printed" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DocStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="InvntSttus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Transfered" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ObjType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DocDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DocDueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CardCode" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="CardName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="NumAtCard" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VatPercent" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatSumFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DiscPrcnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DiscSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DiscSumFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DocCur" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="DocRate" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DocTotal" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DocTotalFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidToDate" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="GrosProfit" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="GrosProfFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Ref1" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="Ref2" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="JrnlMemo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReceiptNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupNum" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DocTime" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SlpCode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TrnspCode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PartSupply" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Confirmed" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="GrossBase" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ImportEnt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateTran" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="SummryType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="UpdInvnt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="UpdCardBal" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Instance" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Flags" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InvntDirec" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CntctCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowSCN" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FatherCard" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="SysRate" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CurSource" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VatSumSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DiscSumSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DocTotalSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidSys" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FatherType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="GrosProfSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsICT" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VolUnit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WeightUnit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Series" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TaxDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Filler" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="DataSource" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="StampNum" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="isCrin" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FinncPriod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserSign" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="selfInv" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VatPaid" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatPaidFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatPaidSys" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="UserSign2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="WddStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="draftKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalExpns" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TotalExpFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TotalExpSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DunnLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="LogInstanc" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Exported" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="StationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Indicator" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="NetProc" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AqcsTax" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="AqcsTaxFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="AqcsTaxSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CashDiscPr" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CashDiscnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CashDiscFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CashDiscSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ShipToCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicTradNum" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="PaymentRef" Type="System.String" DbType="NVarChar(27)" CanBeNull="true" />
      <Column Name="WTSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WTSumFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WTSumSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="RoundDif" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="RoundDifFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="RoundDifSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CheckDigit" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Form1099" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Box1099" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="submitted" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PoPrss" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Rounding" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="RevisionPo" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Segment" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CancelDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PickStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Pick" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BlockDunn" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PeyMethod" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PayBlock" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PayBlckRef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxDscn" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Reserve" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Max1099" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CntrlBnk" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PickRmrk" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="ISRCodLine" Type="System.String" DbType="NVarChar(53)" CanBeNull="true" />
      <Column Name="ExpAppl" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExpApplFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExpApplSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Project" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DeferrTax" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="LetterNum" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WTApplied" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WTAppliedF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BoeReserev" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="WTAppliedS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="EquVatSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="EquVatSumF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="EquVatSumS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Installmnt" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="VATFirst" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NnSbAmnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NnSbAmntSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NbSbAmntFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExepAmnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExepAmntSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExepAmntFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CorrExt" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="CorrInv" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NCorrInv" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CEECFlag" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BaseAmnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseAmntSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseAmntFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CtlAccount" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="BPLId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BPLName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VATRegNum" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="TxInvRptNo" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TxInvRptDt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="KVVATCode" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="WTDetails" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SumAbsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SumRptDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PIndicator" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ManualNum" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UseShpdGd" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BaseVtAt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseVtAtSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseVtAtFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NnSbVAt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NnSbVAtSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NbSbVAtFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExptVAt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExptVAtSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExptVAtFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LYPmtAt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LYPmtAtSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LYPmtAtFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExpAnSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExpAnSys" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExpAnFrgn" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DocSubType" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="DpmStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DpmAmnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmAmntSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmAmntFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmDrawn" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DpmPrcnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidSumFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidSumSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FolioPref" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FolioNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DpmAppl" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmApplFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmApplSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LPgFolioN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Header" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Footer" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Posted" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="OwnerCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BPChCode" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="BPChCntc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayToCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsPaytoBnk" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BnkCntry" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="BankCode" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="BnkAccount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BnkBranch" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="isIns" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="TrackNo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="VersionNum" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="LangCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BPNameOW" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BillToOW" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ShipToOW" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="RetInvoice" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ClsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MInvNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MInvDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SeqCode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Serial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SeriesStr" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="SubStr" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="TaxOnExp" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxOnExpFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxOnExpSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxOnExAp" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxOnExApF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxOnExApS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LastPmnTyp" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="LndCstNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseCorrVat" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BlkCredMmo" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="OpenForLaC" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Excised" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ExcRefDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExcRmvTime" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="SrvGpPrcnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DepositNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CertNum" Type="System.String" DbType="NVarChar(31)" CanBeNull="true" />
      <Column Name="DutyStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AutoCrtFlw" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FlwRefDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FlwRefNum" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VatJENum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DpmVat" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmVatFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmVatSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmAppVat" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmAppVatF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmAppVatS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="InsurOp347" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="IgnRelDoc" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BuildDesc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResidenNum" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Checker" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Payee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CopyNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSIExmpt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PQTGrpSer" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PQTGrpNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PQTGrpHW" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ReopOriDoc" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ReopManCls" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DocManClsd" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ClosingOpt" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SpecDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ordered" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NTSApprov" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NTSWebSite" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="NTSeTaxNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NTSApprNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PayDuMonth" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ExtraMonth" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ExtraDays" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CdcOffset" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SignMsg" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SignDigest" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CertifNum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyVersion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDocGenTyp" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ESeries" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EDocNum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EDocExpFrm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OnlineQuo" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="POSEqNum" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="POSManufSN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="POSCashN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDocStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EDocCntnt" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EDocProces" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EDocErrCod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EDocErrMsg" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EDocCancel" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EDocTest" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EDocPrefix" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CUP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CIG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DpmAsDscnt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Attachment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AtcEntry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupplCode" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="GTSRlvnt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BaseDisc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseDiscSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseDiscFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseDiscPr" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="U_Ref_Demande" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.INV1" Member="INV1">
    <Type Name="INV1">
      <Column Name="DocEntry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LineNum" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TargetType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrgetEntry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BaseRef" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="BaseType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BaseEntry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BaseLine" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LineStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ItemCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Dscription" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ShipDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OpenQty" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Currency" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DiscPrcnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LineTotal" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TotalFrgn" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="OpenSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="OpenSumFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VendorNum" Type="System.String" DbType="NVarChar(17)" CanBeNull="true" />
      <Column Name="SerialNum" Type="System.String" DbType="NVarChar(17)" CanBeNull="true" />
      <Column Name="WhsCode" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="SlpCode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Commission" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TreeType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AcctCode" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="TaxStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="GrossBuyPr" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PriceBefDi" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DocDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Flags" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OpenCreQty" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="UseBaseUn" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="SubCatNum" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="BaseCard" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="TotalSumSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="OpenSumSys" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="InvntSttus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="OcrCode" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="Project" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CodeBars" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="VatPrcnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatGroup" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="PriceAfVAT" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Height1" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Hght1Unit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Height2" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Hght2Unit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Width1" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Wdth1Unit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Width2" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Wdth2Unit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Length1" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Len1Unit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="length2" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Len2Unit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VolUnit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Weight1" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Wght1Unit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Weight2" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Wght2Unit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Factor1" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Factor2" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Factor3" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Factor4" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PackQty" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="UpdInvntry" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BaseDocNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BaseAtCard" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SWW" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="VatSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatSumFrgn" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatSumSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FinncPriod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ObjType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LogInstanc" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BlockNum" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ImportLog" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DedVatSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DedVatSumF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DedVatSumS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="IsAqcuistn" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DistribSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DstrbSumFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DstrbSumSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="GrssProfit" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="GrssProfSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="GrssProfFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VisOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="INMPrice" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PoTrgNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PoTrgEntry" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="DropShip" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PoLineNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="TaxType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="OrigItem" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="BackOrdr" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FreeTxt" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PickStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PickOty" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PickIdNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrnsCode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="VatAppld" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatAppldFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatAppldSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseQty" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseOpnQty" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatDscntPr" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WtLiable" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DeferrTax" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EquVatPer" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="EquVatSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="EquVatSumF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="EquVatSumS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LineVat" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LineVatlF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LineVatS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="unitMsr" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NumPerMsr" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CEECFlag" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ToStock" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ToDiff" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExciseAmt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxPerUnit" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TotInclTax" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CountryOrg" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="StckDstSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ReleasQtty" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LineType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="TranType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OwnerCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StockPrice" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ConsumeFCT" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="LstByDsSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="StckINMPr" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LstBINMPr" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="StckDstFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="StckDstSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LstByDsFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LstByDsSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="StockSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="StockSumFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="StockSumSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="StckSumApp" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="StckAppFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="StckAppSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ShipToCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShipToDesc" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="StckAppD" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="StckAppDFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="StckAppDSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BasePrice" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="GTotal" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="GTotalFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="GTotalSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DistribExp" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DescOW" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DetailsOW" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="GrossBase" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="VatWoDpm" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatWoDpmFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatWoDpmSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CFOPCode" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="CSTCode" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="Usage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TaxOnly" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="WtCalced" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="QtyToShip" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DelivrdQty" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="OrderedQty" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CogsOcrCod" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="CiOppLineN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CogsAcct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ChgAsmBoMW" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ActDelDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OcrCode2" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="OcrCode3" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="OcrCode4" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="OcrCode5" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="TaxDistSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxDistSFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxDistSSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PostTax" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Excisable" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AssblValue" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="RG23APart1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RG23APart2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RG23CPart1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RG23CPart2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CogsOcrCo2" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="CogsOcrCo3" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="CogsOcrCo4" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="CogsOcrCo5" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="LnExcised" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="LocCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StockValue" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="GPTtlBasPr" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="unitMsr2" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NumPerMsr2" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="SpecPrice" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CSTfIPI" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="CSTfPIS" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="CSTfCOFINS" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ExLineNo" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="isSrvCall" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PQTReqQty" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PQTReqDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PcDocType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PcQuantity" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LinManClsd" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VatGrpSrc" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NoInvtryMv" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ActBaseEnt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActBaseLn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActBaseNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OpenRtnQty" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="AgrNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AgrLnNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CredOrigin" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FREE01" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="FREE02" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="FREE03" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.JDT1" Member="JDT1">
    <Type Name="JDT1">
      <Column Name="TransId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Line_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Account" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Debit" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Credit" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="SYSCred" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="SYSDeb" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FCDebit" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FCCredit" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FCCurrency" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="DueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SourceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourceLine" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ShortName" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="IntrnMatch" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExtrMatch" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContraAct" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="LineMemo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ref3Line" Type="System.String" DbType="NVarChar(27)" CanBeNull="true" />
      <Column Name="TransType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="RefDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ref2Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ref1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Ref2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BaseRef" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="Project" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TransCode" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="ProfitCode" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="TaxDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SystemRate" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="MthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ToMthSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="UserSign" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BatchNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FinncPriod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RelTransId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RelLineID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RelType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="LogInstanc" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="VatGroup" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="BaseSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatRate" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Indicator" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="AdjTran" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="RevSource" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ObjType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="VatDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PaymentRef" Type="System.String" DbType="NVarChar(27)" CanBeNull="true" />
      <Column Name="SYSBaseSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="MultMatch" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VatLine" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VatAmount" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="SYSVatSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Closed" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="GrossValue" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CheckAbs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LineType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DebCred" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="SequenceNr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StornoAcc" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="BalDueDeb" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BalDueCred" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BalFcDeb" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BalFcCred" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BalScDeb" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BalScCred" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="IsNet" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DunWizBlck" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DunnLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DunDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TaxType" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TaxPostAcc" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="StaCode" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="StaType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TaxCode" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="ValidFrom" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GrossValFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LvlUpdDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OcrCode2" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="OcrCode3" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="OcrCode4" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="OcrCode5" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="MIEntry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MIVEntry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClsInTP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CenVatCom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MatType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PstngType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValidFrom2" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ValidFrom3" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ValidFrom4" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ValidFrom5" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Location" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WTaxCode" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="EquVatRate" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="EquVatSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="SYSEquSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TotalVat" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="SYSTVat" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WTLiable" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="WTLine" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="WTApplied" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WTAppliedS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WTAppliedF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WTSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WTSumFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WTSumSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PayBlock" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PayBlckRef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LicTradNum" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="InterimTyp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DprId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MatchRef" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Ordered" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CUP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CIG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BPLId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BPLName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VatRegNum" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OPOR" Member="OPOR">
    <Type Name="OPOR">
      <Column Name="DocEntry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DocNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DocType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CANCELED" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Handwrtten" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Printed" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DocStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="InvntSttus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Transfered" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ObjType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DocDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DocDueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CardCode" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="CardName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="NumAtCard" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VatPercent" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatSumFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DiscPrcnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DiscSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DiscSumFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DocCur" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="DocRate" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DocTotal" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DocTotalFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidToDate" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="GrosProfit" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="GrosProfFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Ref1" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="Ref2" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="JrnlMemo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TransId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReceiptNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupNum" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DocTime" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SlpCode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TrnspCode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PartSupply" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Confirmed" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="GrossBase" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ImportEnt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateTran" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="SummryType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="UpdInvnt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="UpdCardBal" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Instance" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Flags" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InvntDirec" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CntctCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShowSCN" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FatherCard" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="SysRate" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CurSource" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VatSumSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DiscSumSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DocTotalSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidSys" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FatherType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="GrosProfSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsICT" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VolUnit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WeightUnit" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Series" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TaxDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Filler" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="DataSource" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="StampNum" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="isCrin" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FinncPriod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserSign" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="selfInv" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="VatPaid" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatPaidFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatPaidSys" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="UserSign2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="WddStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="draftKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalExpns" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TotalExpFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TotalExpSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DunnLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="LogInstanc" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Exported" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="StationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Indicator" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="NetProc" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AqcsTax" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="AqcsTaxFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="AqcsTaxSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CashDiscPr" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CashDiscnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CashDiscFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CashDiscSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ShipToCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LicTradNum" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="PaymentRef" Type="System.String" DbType="NVarChar(27)" CanBeNull="true" />
      <Column Name="WTSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WTSumFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WTSumSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="RoundDif" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="RoundDifFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="RoundDifSy" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CheckDigit" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Form1099" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Box1099" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="submitted" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PoPrss" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Rounding" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="RevisionPo" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Segment" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="ReqDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CancelDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PickStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Pick" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BlockDunn" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PeyMethod" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PayBlock" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PayBlckRef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxDscn" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Reserve" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Max1099" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CntrlBnk" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="PickRmrk" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="ISRCodLine" Type="System.String" DbType="NVarChar(53)" CanBeNull="true" />
      <Column Name="ExpAppl" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExpApplFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExpApplSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Project" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DeferrTax" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="LetterNum" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WTApplied" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="WTAppliedF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BoeReserev" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AgentCode" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="WTAppliedS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="EquVatSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="EquVatSumF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="EquVatSumS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="Installmnt" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="VATFirst" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NnSbAmnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NnSbAmntSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NbSbAmntFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExepAmnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExepAmntSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExepAmntFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="VatDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CorrExt" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="CorrInv" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NCorrInv" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CEECFlag" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BaseAmnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseAmntSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseAmntFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="CtlAccount" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="BPLId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BPLName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VATRegNum" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" />
      <Column Name="TxInvRptNo" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TxInvRptDt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="KVVATCode" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="WTDetails" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SumAbsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SumRptDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PIndicator" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ManualNum" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UseShpdGd" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BaseVtAt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseVtAtSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseVtAtFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NnSbVAt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NnSbVAtSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="NbSbVAtFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExptVAt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExptVAtSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExptVAtFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LYPmtAt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LYPmtAtSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LYPmtAtFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExpAnSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExpAnSys" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="ExpAnFrgn" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DocSubType" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="DpmStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DpmAmnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmAmntSC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmAmntFC" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmDrawn" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DpmPrcnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidSum" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidSumFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="PaidSumSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="FolioPref" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FolioNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DpmAppl" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmApplFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmApplSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LPgFolioN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Header" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Footer" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Posted" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="OwnerCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BPChCode" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="BPChCntc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayToCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsPaytoBnk" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BnkCntry" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="BankCode" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="BnkAccount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BnkBranch" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="isIns" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="TrackNo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="VersionNum" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="LangCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BPNameOW" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BillToOW" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ShipToOW" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="RetInvoice" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ClsDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MInvNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MInvDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SeqCode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Serial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SeriesStr" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="SubStr" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="TaxOnExp" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxOnExpFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxOnExpSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxOnExAp" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxOnExApF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="TaxOnExApS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="LastPmnTyp" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="LndCstNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseCorrVat" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BlkCredMmo" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="OpenForLaC" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Excised" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ExcRefDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExcRmvTime" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="SrvGpPrcnt" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DepositNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CertNum" Type="System.String" DbType="NVarChar(31)" CanBeNull="true" />
      <Column Name="DutyStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="AutoCrtFlw" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="FlwRefDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FlwRefNum" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VatJENum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DpmVat" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmVatFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmVatSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmAppVat" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmAppVatF" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="DpmAppVatS" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="InsurOp347" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="IgnRelDoc" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BuildDesc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ResidenNum" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Checker" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Payee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CopyNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSIExmpt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="PQTGrpSer" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PQTGrpNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PQTGrpHW" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ReopOriDoc" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ReopManCls" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DocManClsd" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ClosingOpt" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SpecDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ordered" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NTSApprov" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="NTSWebSite" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="NTSeTaxNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NTSApprNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PayDuMonth" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ExtraMonth" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ExtraDays" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CdcOffset" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SignMsg" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SignDigest" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CertifNum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeyVersion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDocGenTyp" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ESeries" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EDocNum" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EDocExpFrm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OnlineQuo" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="POSEqNum" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="POSManufSN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="POSCashN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDocStatus" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EDocCntnt" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EDocProces" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EDocErrCod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EDocErrMsg" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EDocCancel" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EDocTest" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="EDocPrefix" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CUP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CIG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DpmAsDscnt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Attachment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AtcEntry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupplCode" Type="System.String" DbType="NVarChar(254)" CanBeNull="true" />
      <Column Name="GTSRlvnt" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="BaseDisc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseDiscSc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseDiscFc" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="BaseDiscPr" Type="System.Decimal" DbType="Decimal(19,6)" CanBeNull="true" />
      <Column Name="U_Ref_Demande" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
    </Type>
  </Table>
</Database>