//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCONIER
    {
        public ACCONIER()
        {
            this.ESCALE = new HashSet<ESCALE>();
        }
    
        public int IdAcc { get; set; }
        public string CodeAcc { get; set; }
        public string NomAcc { get; set; }
        public string StatutAcc { get; set; }
        public string AIAcc { get; set; }
        public string CCAcc { get; set; }
    
        public virtual ICollection<ESCALE> ESCALE { get; set; }
    }
}
