//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BON_ENLEVEMENT
    {
        public BON_ENLEVEMENT()
        {
            this.NOTE = new HashSet<NOTE>();
        }
    
        public int IdBAE { get; set; }
        public Nullable<System.DateTime> DateBAE { get; set; }
        public Nullable<System.DateTime> DVBAE { get; set; }
        public string ELGBAE { get; set; }
        public string DLGBAE { get; set; }
        public Nullable<System.DateTime> DELGBAE { get; set; }
        public Nullable<System.DateTime> DFLGBAE { get; set; }
        public string AIBAE { get; set; }
        public string AIVBAE { get; set; }
        public Nullable<int> IdBL { get; set; }
        public Nullable<int> IdU { get; set; }
        public Nullable<int> IdUV { get; set; }
    
        public virtual CONNAISSEMENT CONNAISSEMENT { get; set; }
        public virtual ICollection<NOTE> NOTE { get; set; }
    }
}
