//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_TVA
    {
        public CODE_TVA()
        {
            this.ARTICLE = new HashSet<ARTICLE>();
            this.CLIENT = new HashSet<CLIENT>();
        }
    
        public string CodeTVA { get; set; }
        public string LibTVA { get; set; }
        public Nullable<float> TauxTVA { get; set; }
        public string CCompte { get; set; }
    
        public virtual ICollection<ARTICLE> ARTICLE { get; set; }
        public virtual ICollection<CLIENT> CLIENT { get; set; }
    }
}
