//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUBAGE_VEHICULE
    {
        public int IdCubage { get; set; }
        public int IdVeh { get; set; }
        public Nullable<float> LongAVeh { get; set; }
        public Nullable<float> LargAVeh { get; set; }
        public Nullable<float> HautAVeh { get; set; }
        public Nullable<float> VolAVeh { get; set; }
        public Nullable<float> LongCVeh { get; set; }
        public Nullable<float> LargCVeh { get; set; }
        public Nullable<float> HautCVeh { get; set; }
        public Nullable<float> VolCVeh { get; set; }
        public string TypeCVeh { get; set; }
        public Nullable<System.DateTime> DateCV { get; set; }
        public string AICB { get; set; }
        public Nullable<System.DateTime> DateVal { get; set; }
    
        public virtual CUBAGE CUBAGE { get; set; }
        public virtual VEHICULE VEHICULE { get; set; }
    }
}
