//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMANDE_REDUCTION
    {
        public DEMANDE_REDUCTION()
        {
            this.NOTE = new HashSet<NOTE>();
        }
    
        public int IdDDR { get; set; }
        public Nullable<System.DateTime> DateDDR { get; set; }
        public Nullable<System.DateTime> DatevDDR { get; set; }
        public string LibDDR { get; set; }
        public Nullable<double> Pourcent { get; set; }
        public Nullable<int> MHT { get; set; }
        public Nullable<float> TauxTVA { get; set; }
        public string ObsDDR { get; set; }
        public Nullable<short> CodeArticle { get; set; }
        public Nullable<int> IdBL { get; set; }
        public Nullable<int> IdU { get; set; }
        public Nullable<int> IdUV { get; set; }
        public string AIVDDR { get; set; }
        public string StatutRed { get; set; }
    
        public virtual ARTICLE ARTICLE { get; set; }
        public virtual CONNAISSEMENT CONNAISSEMENT { get; set; }
        public virtual ICollection<NOTE> NOTE { get; set; }
    }
}
