//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMANDE_LIVRAISON
    {
        public DEMANDE_LIVRAISON()
        {
            this.NOTE = new HashSet<NOTE>();
        }
    
        public int IdDBL { get; set; }
        public Nullable<System.DateTime> DateDBL { get; set; }
        public Nullable<System.DateTime> DVDBL { get; set; }
        public string AIDBL { get; set; }
        public string AIVDBL { get; set; }
        public Nullable<int> IdBL { get; set; }
        public Nullable<int> IdU { get; set; }
        public Nullable<int> IdUV { get; set; }
        public Nullable<System.DateTime> DateDepotDBL { get; set; }
    
        public virtual CONNAISSEMENT CONNAISSEMENT { get; set; }
        public virtual ICollection<NOTE> NOTE { get; set; }
    }
}
