//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELEMENT_FACTURATION
    {
        public ELEMENT_FACTURATION()
        {
            this.LIGNE_PROFORMA = new HashSet<LIGNE_PROFORMA>();
        }
    
        public int IdJEF { get; set; }
        public Nullable<System.DateTime> DateJEF { get; set; }
        public string EltFacture { get; set; }
        public string LibEF { get; set; }
        public Nullable<int> IdLP { get; set; }
        public Nullable<double> PUEF { get; set; }
        public Nullable<double> PUEFBase { get; set; }
        public Nullable<double> QTEEF { get; set; }
        public string UnitEF { get; set; }
        public Nullable<double> PTDIT { get; set; }
        public Nullable<int> IdEsc { get; set; }
        public Nullable<int> IdMan { get; set; }
        public Nullable<int> IdBL { get; set; }
        public Nullable<int> IdVeh { get; set; }
        public Nullable<int> IdCtr { get; set; }
        public Nullable<int> IdMafi { get; set; }
        public Nullable<int> IdGC { get; set; }
        public Nullable<int> IdOS { get; set; }
        public Nullable<int> IdLS { get; set; }
        public string CodeTVA { get; set; }
        public Nullable<float> TauxTVA { get; set; }
        public string CCArticle { get; set; }
        public string CCCP { get; set; }
        public Nullable<int> IdFD { get; set; }
        public Nullable<int> IdDDR { get; set; }
        public string DestEF { get; set; }
        public Nullable<System.DateTime> DelaiEF { get; set; }
        public string StatutEF { get; set; }
        public Nullable<int> IdFactDIT { get; set; }
        public Nullable<int> IdFA { get; set; }
        public string CodeArticle { get; set; }
        public Nullable<int> IdFSoc { get; set; }
        public string CCARTICLE1 { get; set; }
        public Nullable<int> REF_IDJEF { get; set; }
        public Nullable<int> ID_QUOTATION { get; set; }
    
        public virtual CONNAISSEMENT CONNAISSEMENT { get; set; }
        public virtual LIGNE_PRIX LIGNE_PRIX { get; set; }
        public virtual ICollection<LIGNE_PROFORMA> LIGNE_PROFORMA { get; set; }
    }
}
