//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLACEMENT
    {
        public EMPLACEMENT()
        {
            this.OCCUPATION = new HashSet<OCCUPATION>();
        }
    
        public int IdEmpl { get; set; }
        public string LigEmpl { get; set; }
        public string ColEmpl { get; set; }
        public Nullable<float> LongMin { get; set; }
        public Nullable<float> LongMax { get; set; }
        public Nullable<float> LargMin { get; set; }
        public Nullable<float> LargMax { get; set; }
        public string StatutEmpl { get; set; }
        public Nullable<int> IdParc { get; set; }
        public string TypeEmpl { get; set; }
        public Nullable<System.DateTime> DCEMPL { get; set; }
    
        public virtual PARC PARC { get; set; }
        public virtual ICollection<OCCUPATION> OCCUPATION { get; set; }
    }
}
