//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCALE
    {
        public ESCALE()
        {
            this.CUBAGE = new HashSet<CUBAGE>();
            this.MANIFESTE = new HashSet<MANIFESTE>();
            this.NOTE = new HashSet<NOTE>();
            this.ORDRE_SERVICE = new HashSet<ORDRE_SERVICE>();
            this.CONNAISSEMENT = new HashSet<CONNAISSEMENT>();
        }
    
        public int IdEsc { get; set; }
        public Nullable<int> NumEsc { get; set; }
        public string NumVoySCR { get; set; }
        public string NumVoyDIT { get; set; }
        public string NomCpt { get; set; }
        public Nullable<System.DateTime> DCEsc { get; set; }
        public Nullable<System.DateTime> DDEsc { get; set; }
        public Nullable<System.DateTime> DPAEsc { get; set; }
        public Nullable<System.DateTime> DRAEsc { get; set; }
        public Nullable<System.DateTime> DDechEsc { get; set; }
        public Nullable<short> NbrePManEsc { get; set; }
        public string RGPEsc { get; set; }
        public string RREsc { get; set; }
        public string RAEsc { get; set; }
        public string RCEsc { get; set; }
        public string AIEsc { get; set; }
        public string SOP { get; set; }
        public Nullable<int> IdNav { get; set; }
        public Nullable<int> IdArm { get; set; }
        public Nullable<int> IdAcc { get; set; }
        public Nullable<int> IdFArm { get; set; }
        public Nullable<System.DateTime> DateFArm { get; set; }
        public string StatEsc { get; set; }
        public Nullable<System.DateTime> SailingDate { get; set; }
        public string NumManifestSydonia { get; set; }
        public Nullable<int> IdUserFIntern { get; set; }
        public string FIntern { get; set; }
    
        public virtual ACCONIER ACCONIER { get; set; }
        public virtual ARMATEUR ARMATEUR { get; set; }
        public virtual ICollection<CUBAGE> CUBAGE { get; set; }
        public virtual NAVIRE NAVIRE { get; set; }
        public virtual ICollection<MANIFESTE> MANIFESTE { get; set; }
        public virtual ICollection<NOTE> NOTE { get; set; }
        public virtual ICollection<ORDRE_SERVICE> ORDRE_SERVICE { get; set; }
        public virtual ICollection<CONNAISSEMENT> CONNAISSEMENT { get; set; }
    }
}
