//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIST_CONNAISSEMENT
    {
        public int IdHistBL { get; set; }
        public Nullable<int> IdBL { get; set; }
        public string NumBL { get; set; }
        public string LPBL { get; set; }
        public string DPBL { get; set; }
        public string BLGN { get; set; }
        public string BLIL { get; set; }
        public string BLSocar { get; set; }
        public string NumSocar { get; set; }
        public string BLFO { get; set; }
        public string BLLT { get; set; }
        public string CCBL { get; set; }
        public Nullable<int> CCBLMontant { get; set; }
        public string BlBloque { get; set; }
        public string BLER { get; set; }
        public string BLERNote { get; set; }
        public string ConsigneeBL { get; set; }
        public string AdresseBL { get; set; }
        public string NotifyBL { get; set; }
        public string StatutBL { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdMan { get; set; }
        public Nullable<int> IdEsc { get; set; }
        public string EmailBL { get; set; }
        public string SensBL { get; set; }
        public string BLDette { get; set; }
        public Nullable<int> DetteMontant { get; set; }
        public string BLBloqueNote { get; set; }
        public string DestBL { get; set; }
        public Nullable<int> IdU { get; set; }
    }
}
