//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIGNE_PROFORMA
    {
        public int IdFP { get; set; }
        public int IdJEF { get; set; }
        public string StatutLP { get; set; }
        public Nullable<double> PUEF { get; set; }
        public Nullable<double> QTEEF { get; set; }
        public Nullable<float> TauxTVA { get; set; }
    
        public virtual ELEMENT_FACTURATION ELEMENT_FACTURATION { get; set; }
        public virtual PROFORMA PROFORMA { get; set; }
    }
}
