//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAVIRE
    {
        public NAVIRE()
        {
            this.ESCALE = new HashSet<ESCALE>();
        }
    
        public int IdNav { get; set; }
        public string CodeNav { get; set; }
        public string NomNav { get; set; }
        public string StatutNav { get; set; }
        public string AINav { get; set; }
        public string CodeRadio { get; set; }
        public Nullable<int> IdArm { get; set; }
        public string CodeTracking { get; set; }
        public string CodeNDS { get; set; }
    
        public virtual ICollection<ESCALE> ESCALE { get; set; }
    }
}
