//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NAVYEntities1 : DbContext
    {
        public NAVYEntities1()
            : base("name=VSOMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACCONIER> ACCONIER { get; set; }
        public DbSet<ARMATEUR> ARMATEUR { get; set; }
        public DbSet<ARTICLE> ARTICLE { get; set; }
        public DbSet<BON_ENLEVEMENT> BON_ENLEVEMENT { get; set; }
        public DbSet<BON_SORTIE> BON_SORTIE { get; set; }
        public DbSet<CLIENT> CLIENT { get; set; }
        public DbSet<CODE_TVA> CODE_TVA { get; set; }
        public DbSet<CONNAISSEMENT> CONNAISSEMENT { get; set; }
        public DbSet<CUBAGE> CUBAGE { get; set; }
        public DbSet<CUBAGE_VEHICULE> CUBAGE_VEHICULE { get; set; }
        public DbSet<DEMANDE_LIVRAISON> DEMANDE_LIVRAISON { get; set; }
        public DbSet<DEMANDE_REDUCTION> DEMANDE_REDUCTION { get; set; }
        public DbSet<ELEMENT_FACTURATION> ELEMENT_FACTURATION { get; set; }
        public DbSet<EMPLACEMENT> EMPLACEMENT { get; set; }
        public DbSet<ESCALE> ESCALE { get; set; }
        public DbSet<FACTURE> FACTURE { get; set; }
        public DbSet<FAMILLE_ARTICLE> FAMILLE_ARTICLE { get; set; }
        public DbSet<HIST_CONNAISSEMENT> HIST_CONNAISSEMENT { get; set; }
        public DbSet<LIGNE_PRIX> LIGNE_PRIX { get; set; }
        public DbSet<LIGNE_PROFORMA> LIGNE_PROFORMA { get; set; }
        public DbSet<MANIFESTE> MANIFESTE { get; set; }
        public DbSet<NAVIRE> NAVIRE { get; set; }
        public DbSet<NOTE> NOTE { get; set; }
        public DbSet<OCCUPATION> OCCUPATION { get; set; }
        public DbSet<OPERATION> OPERATION { get; set; }
        public DbSet<OPERATION_CONNAISSEMENT> OPERATION_CONNAISSEMENT { get; set; }
        public DbSet<OPERATION_MANIFESTE> OPERATION_MANIFESTE { get; set; }
        public DbSet<OPERATION_VEHICULE> OPERATION_VEHICULE { get; set; }
        public DbSet<ORDRE_SERVICE> ORDRE_SERVICE { get; set; }
        public DbSet<PARAMETRE> PARAMETRE { get; set; }
        public DbSet<PARC> PARC { get; set; }
        public DbSet<PAYEMENT> PAYEMENT { get; set; }
        public DbSet<PROFORMA> PROFORMA { get; set; }
        public DbSet<TYPE_OPERATION> TYPE_OPERATION { get; set; }
        public DbSet<TYPE_VEHICULE> TYPE_VEHICULE { get; set; }
        public DbSet<UTILISATEUR> UTILISATEUR { get; set; }
        public DbSet<VEHICULE> VEHICULE { get; set; }
    }
}
