//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTE
    {
        public int IdNote { get; set; }
        public string DescNote { get; set; }
        public Nullable<System.DateTime> DateNote { get; set; }
        public Nullable<int> IdU { get; set; }
        public Nullable<int> IdEsc { get; set; }
        public Nullable<int> IdMan { get; set; }
        public Nullable<int> IdBL { get; set; }
        public Nullable<int> IdVeh { get; set; }
        public Nullable<int> IdCtr { get; set; }
        public Nullable<int> IdMafi { get; set; }
        public Nullable<int> IdGC { get; set; }
        public Nullable<int> IdFP { get; set; }
        public Nullable<int> IdFD { get; set; }
        public Nullable<int> IdOS { get; set; }
        public Nullable<int> IdCubage { get; set; }
        public Nullable<int> IdBAE { get; set; }
        public Nullable<int> IdDRC { get; set; }
        public Nullable<int> IdDBL { get; set; }
        public Nullable<int> IdDDR { get; set; }
        public Nullable<int> IdDV { get; set; }
        public Nullable<int> IdDEXT { get; set; }
        public Nullable<int> IdFactDIT { get; set; }
        public Nullable<int> IdPay { get; set; }
        public string TitreNote { get; set; }
    
        public virtual BON_ENLEVEMENT BON_ENLEVEMENT { get; set; }
        public virtual CONNAISSEMENT CONNAISSEMENT { get; set; }
        public virtual CUBAGE CUBAGE { get; set; }
        public virtual DEMANDE_LIVRAISON DEMANDE_LIVRAISON { get; set; }
        public virtual DEMANDE_REDUCTION DEMANDE_REDUCTION { get; set; }
        public virtual ESCALE ESCALE { get; set; }
        public virtual FACTURE FACTURE { get; set; }
        public virtual MANIFESTE MANIFESTE { get; set; }
        public virtual ORDRE_SERVICE ORDRE_SERVICE { get; set; }
        public virtual PAYEMENT PAYEMENT { get; set; }
        public virtual PROFORMA PROFORMA { get; set; }
        public virtual VEHICULE VEHICULE { get; set; }
    }
}
