//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARC
    {
        public PARC()
        {
            this.EMPLACEMENT = new HashSet<EMPLACEMENT>();
        }
    
        public int IdParc { get; set; }
        public string NomParc { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<EMPLACEMENT> EMPLACEMENT { get; set; }
    }
}
