//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFORMA
    {
        public PROFORMA()
        {
            this.FACTURE = new HashSet<FACTURE>();
            this.LIGNE_PROFORMA = new HashSet<LIGNE_PROFORMA>();
            this.NOTE = new HashSet<NOTE>();
        }
    
        public int IdFP { get; set; }
        public string RefAS400 { get; set; }
        public Nullable<System.DateTime> DCFP { get; set; }
        public Nullable<System.DateTime> DVFP { get; set; }
        public string AIFP { get; set; }
        public string AIVFP { get; set; }
        public string StatutFP { get; set; }
        public Nullable<int> MHT { get; set; }
        public Nullable<int> MTVA { get; set; }
        public Nullable<int> MTTC { get; set; }
        public Nullable<int> IdBL { get; set; }
        public Nullable<int> IdArm { get; set; }
        public Nullable<int> IdU { get; set; }
        public Nullable<int> IdUV { get; set; }
        public Nullable<int> IdClient { get; set; }
        public string ClientFacture { get; set; }
        public Nullable<int> MHT_EF { get; set; }
        public Nullable<int> MTVA_EF { get; set; }
        public Nullable<int> MTTC_EF { get; set; }
        public Nullable<int> PROMO { get; set; }
    
        public virtual ICollection<FACTURE> FACTURE { get; set; }
        public virtual ICollection<LIGNE_PROFORMA> LIGNE_PROFORMA { get; set; }
        public virtual ICollection<NOTE> NOTE { get; set; }
    }
}
