//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_VEHICULE
    {
        public string CodeTypeVeh { get; set; }
        public string LibTypeVeh { get; set; }
        public Nullable<int> DeVol { get; set; }
        public Nullable<short> LimVol { get; set; }
    }
}
