//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_OPERATION
    {
        public TYPE_OPERATION()
        {
            this.OCCUPATION = new HashSet<OCCUPATION>();
            this.OPERATION_VEHICULE = new HashSet<OPERATION_VEHICULE>();
        }
    
        public int IdTypeOp { get; set; }
        public string LibTypeOp { get; set; }
        public string EltTypeOp { get; set; }
        public Nullable<int> IdArm { get; set; }
        public string Statut { get; set; }
        public string CodeMvt { get; set; }
        public string CodeDIT { get; set; }
    
        public virtual ICollection<OCCUPATION> OCCUPATION { get; set; }
        public virtual ICollection<OPERATION_VEHICULE> OPERATION_VEHICULE { get; set; }
    }
}
