//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VesselStopOverDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILISATEUR
    {
        public int IdU { get; set; }
        public string LU { get; set; }
        public string NU { get; set; }
        public string MPU { get; set; }
        public string EU { get; set; }
        public Nullable<short> OA { get; set; }
        public string AIU { get; set; }
        public Nullable<int> IdAcc { get; set; }
        public string Caisse { get; set; }
        public Nullable<int> IdParc { get; set; }
        public string pwd { get; set; }
    }
}
